In [ ]:
n=int(input("enter the number "))
if n%2==0:
  print("even ")
print("odd")

enter the number 3
odd


In [ ]:
m1=34
m2=50
m3=44
m4=43
m5=50
m6=29
sum = m1+m2+m3+m4+m5+m6
avg = sum/6
print(sum )
print(avg )


250
41.666666666666664


In [ ]:
sum = 0
for i in range (2,22):
  if i%2==0:
     sum += i
print(sum )



110


In [ ]:
for i in range (2,22):
  if i%2==0:
    print(i)

2
4
6
8
10
12
14
16
18
20


In [ ]:
for i in range (2,22):
  if i%2==0:
    print(i+1)

3
5
7
9
11
13
15
17
19
21


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
a

[1 2 3 4]


array([1, 2, 3, 4])

In [ ]:
b=np.array([[1,2,3,4],[1,2,5,7]])
print(b)
b




2

In [ ]:
b.shape

(2, 4)

In [ ]:
b.ndim

2

In [ ]:
len(b)

2

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.sort()
b

array([[1, 2, 3, 4],
       [1, 2, 5, 7]])

In [ ]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [ ]:
k = np.eye(3)
k

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.diag([1,2])
a

array([[1, 0],
       [0, 2]])

In [ ]:
x = np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
i=[12.23,13.32,100,36.32]
print("original list:,i")
a=np.array(i)
print("one-d numpy array",a)

original list:,i
one-d numpy array [ 12.23  13.32 100.    36.32]


In [ ]:
import random

random_numbers = [random.randint(1, 10) for _ in range(5)]
print(random_numbers)

[2, 6, 1, 10, 1]


In [2]:
from google.colab import files
files.download('Untitled2.ipynb')  # Replace with your file name and extension


FileNotFoundError: Cannot find file: Untitled2.ipynb